### ISSUE TITLE
Hue shift observed

### ISSUE THREAD

**Issue by frmeier** [google/guetzli#106]
I've played around with Guetzli and observed a shift in hue for red in one case. I've attached the pictures:

* Before Guetzli
![img_5033k](https://cloud.githubusercontent.com/assets/4662259/24149332/7425d9d0-0e42-11e7-9bc6-f9592335634c.jpg)
* After Guetzli
![img_5033kg](https://cloud.githubusercontent.com/assets/4662259/24149378/9f0958a2-0e42-11e7-8829-d10fec8a7653.jpg)

It is the red piece that faces the hue shift. I've measured the change using the OS X 'Digital Color Meter' tool as follows:

| Sample | RGB | L*a*b |
|---------|-----|-------|
| Before | 202 93 88 | 56.15 60.43 30.07 |
| After | 215 90 92 | 58.21 68.10 31.67 |

Measured approximately at the center of the red area, averaged over 5x5 pixels.

Command used was `guetzli IMG_5033k{,g}.jpg` Compiled from source on MacOS today, last commit dc6450a. Source picture was taken on an iPhone 6 and lightly processed in Lightroom Mobile.

**Comment by robryk** [comment]
The "before" image has a non-sRGB color profile:

```
  Profiles:
    Profile-icc: 548 bytes
      Description: Display P3
      Manufacturer: Display P3
      Model: Display P3
      Copyright: Copyright Apple Inc., 2015
```

Guetzli [supports only sRGB color profile](https://github.com/google/guetzli#using), and strips color profile metadata from images it compresses. Please convert the image to the sRGB color profile before running Guetzli on it.

Feel free to reopen if that doesn't solve the problem or if that isn't a good solution for any reason.
